require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConfirmationsController do

  # This should return the minimal set of attributes required to create a valid
  # Confirmation. As you add validations to Confirmation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all confirmations as @confirmations" do
      confirmation = Confirmation.create! valid_attributes
      get :index
      assigns(:confirmations).should eq([confirmation])
    end
  end

  describe "GET show" do
    it "assigns the requested confirmation as @confirmation" do
      confirmation = Confirmation.create! valid_attributes
      get :show, :id => confirmation.id.to_s
      assigns(:confirmation).should eq(confirmation)
    end
  end

  describe "GET new" do
    it "assigns a new confirmation as @confirmation" do
      get :new
      assigns(:confirmation).should be_a_new(Confirmation)
    end
  end

  describe "GET edit" do
    it "assigns the requested confirmation as @confirmation" do
      confirmation = Confirmation.create! valid_attributes
      get :edit, :id => confirmation.id.to_s
      assigns(:confirmation).should eq(confirmation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Confirmation" do
        expect {
          post :create, :confirmation => valid_attributes
        }.to change(Confirmation, :count).by(1)
      end

      it "assigns a newly created confirmation as @confirmation" do
        post :create, :confirmation => valid_attributes
        assigns(:confirmation).should be_a(Confirmation)
        assigns(:confirmation).should be_persisted
      end

      it "redirects to the created confirmation" do
        post :create, :confirmation => valid_attributes
        response.should redirect_to(Confirmation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved confirmation as @confirmation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Confirmation.any_instance.stub(:save).and_return(false)
        post :create, :confirmation => {}
        assigns(:confirmation).should be_a_new(Confirmation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Confirmation.any_instance.stub(:save).and_return(false)
        post :create, :confirmation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested confirmation" do
        confirmation = Confirmation.create! valid_attributes
        # Assuming there are no other confirmations in the database, this
        # specifies that the Confirmation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Confirmation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => confirmation.id, :confirmation => {'these' => 'params'}
      end

      it "assigns the requested confirmation as @confirmation" do
        confirmation = Confirmation.create! valid_attributes
        put :update, :id => confirmation.id, :confirmation => valid_attributes
        assigns(:confirmation).should eq(confirmation)
      end

      it "redirects to the confirmation" do
        confirmation = Confirmation.create! valid_attributes
        put :update, :id => confirmation.id, :confirmation => valid_attributes
        response.should redirect_to(confirmation)
      end
    end

    describe "with invalid params" do
      it "assigns the confirmation as @confirmation" do
        confirmation = Confirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Confirmation.any_instance.stub(:save).and_return(false)
        put :update, :id => confirmation.id.to_s, :confirmation => {}
        assigns(:confirmation).should eq(confirmation)
      end

      it "re-renders the 'edit' template" do
        confirmation = Confirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Confirmation.any_instance.stub(:save).and_return(false)
        put :update, :id => confirmation.id.to_s, :confirmation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested confirmation" do
      confirmation = Confirmation.create! valid_attributes
      expect {
        delete :destroy, :id => confirmation.id.to_s
      }.to change(Confirmation, :count).by(-1)
    end

    it "redirects to the confirmations list" do
      confirmation = Confirmation.create! valid_attributes
      delete :destroy, :id => confirmation.id.to_s
      response.should redirect_to(confirmations_url)
    end
  end

end
